In [2]:
import numpy as np

In [ ]:
# Random Sampling

In [3]:
import random

In [4]:
np.random.random(1)

array([0.48883064])

In [5]:
np.random.random((3,3))

array([[0.12499808, 0.3058094 , 0.43224733],
       [0.9624666 , 0.56262839, 0.36089855],
       [0.35739909, 0.83057989, 0.517086  ]])

In [6]:
np.random.randint(1,4)

2

In [8]:
np.random.randint(1,4,(4,4))

array([[2, 3, 1, 1],
       [2, 3, 2, 3],
       [1, 2, 3, 1],
       [2, 1, 2, 3]])

In [9]:
np.random.randint(1,4,(2,4,4))

array([[[1, 1, 1, 3],
        [2, 2, 3, 2],
        [2, 1, 1, 2],
        [2, 3, 2, 2]],

       [[1, 1, 2, 1],
        [2, 3, 1, 2],
        [3, 1, 3, 1],
        [1, 3, 1, 3]]])

In [10]:
np.random.seed(10)

In [11]:
2**32-1

4294967295

In [14]:
np.random.rand(3)

array([0.77132064, 0.02075195, 0.63364823])

In [15]:
np.random.randn(3,3)

array([[-0.01002595,  1.67080819, -0.66437971],
       [-0.60555494, -0.65099088,  0.51256776],
       [ 0.26238882, -0.58273165,  1.36842193]])

In [16]:
x=[1,2,3,4]

In [18]:
np.random.choice(x)

3

In [23]:
for i in range(20):
   print(np.random.choice(x))

2
1
1
3
2
4
3
2
2
2
4
2
3
2
1
3
3
3
2
1


In [24]:
np.random.permutation(x)

array([3, 1, 4, 2])

In [25]:
#STRING Operations,Comparison and information

In [26]:
ch_name = "Indian AI Production"
str1 = "Learning Python Numpy"

In [27]:
np.char.add(ch_name,str1)

array('Indian AI ProductionLearning Python Numpy', dtype='<U41')

In [28]:
np.char.lower(ch_name)

array('indian ai production', dtype='<U20')

In [29]:
np.char.upper(str1)

array('LEARNING PYTHON NUMPY', dtype='<U21')

In [30]:
np.char.center(str1,60)

array('                   Learning Python Numpy                    ',
      dtype='<U60')

In [31]:
np.char.center(str1,60,fillchar ="*")

array('*******************Learning Python Numpy********************',
      dtype='<U60')

In [32]:
np.char.split(ch_name)

array(list(['Indian', 'AI', 'Production']), dtype=object)

In [33]:
np.char.splitlines("hello\nINDIAN")

array(list(['hello', 'INDIAN']), dtype=object)

In [35]:
str4 = "dmy"
str5 = "dmy"

In [36]:
np.char.join([":","/"],[str4,str5])

array(['d:m:y', 'd/m/y'], dtype='<U5')

In [37]:
np.char.replace(ch_name,"AI","Artificial Intelligence")

array('Indian Artificial Intelligence Production', dtype='<U41')