In [ ]:
# numpy basic


In [35]:
import numpy as np

In [62]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [63]:
type(arr_1d)

numpy.ndarray

In [64]:
arr_1d.ndim

1

In [65]:
arr_2d =np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)


[[1 2 3 4]
 [5 6 7 8]]


In [66]:
arr_2d.ndim

2

In [67]:
arr_1d.size

4

In [68]:
arr_2d.size

8

In [69]:
arr_2d.shape

(2, 4)

In [70]:
arr_1d.dtype

dtype('int64')

In [71]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [72]:
mx_1s = np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [73]:
mx_1s.dtype

dtype('float64')

In [74]:
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [75]:
mx_1s = np.ones((3,4),dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [76]:
mx_1s = np.zeros((4,6))
print(mx_1s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [77]:
mx_1s = np.zeros((4,6),dtype = bool)
print(mx_1s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [78]:
mx_1s = np.zeros((4,6),dtype = str)
print(mx_1s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [79]:
em_str = ''
print(bool(em_str))

False


In [80]:
em_mx = np.empty((3,3))
print(em_mx)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


In [81]:
# NumPy Functions

In [82]:
# Arange()


In [89]:
ar_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [90]:
even_ar = np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


In [86]:
# Linspace()

In [91]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [96]:
# reshape()

In [97]:
ar_2d = ar_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [98]:
ar_23d = ar_1d.reshape(2,3,2)
print(ar_23d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [99]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [100]:
# ravel()

In [101]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
# flatten()

In [103]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [104]:
#transpose()

In [105]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [106]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])